Added description of chiliproject_migrate.rb
osuosl/snippets pull request #5
Opened 2017-05-05 18:12 UTC by DesertBeagle

2017-05-05 19:00 UTC, knightsamar requested changes
Some small changes required and a bit of spacing, but good start!

2017-05-05 19:00 UTC, knightsamar commented on README.md
> +To use this you first must from the project id of the project you are trying to migrate.
_obtain_ the project id.

2017-05-05 19:00 UTC, knightsamar commented on README.md
> +Then, run `./script/console production` in the chiliproject root directory to gain access to the ORM console.
Actually, it's the standard Ruby REPL with all production settings loaded (and hence pointed to the production database)

2017-05-05 19:00 UTC, knightsamar commented on README.md
> +Once you have access, you paste the script in. Sure, it isn't pretty, but it works.
How do we determine 'access' ? :)

2017-05-12 21:06 UTC, DesertBeagle commented
@knightsamar Changers made!

2017-05-24 04:58 UTC, knightsamar requested changes

2017-05-24 04:58 UTC, knightsamar commented on README.md
> +If you can't find your project, make sure to check the settings in `chiliproject/config/database.yml`.
How do we determine whether we have found or not found our project on the REPL?

2017-05-24 04:58 UTC, knightsamar commented on README.md
> +RVM is a great tool fror managing Ruby versions.
A link could be added to RVM installation page from this.

2017-05-24 05:00 UTC, knightsamar commented
Ah just realized, I had a review pending submission.

2017-06-06 21:22 UTC, DesertBeagle commented
@knightsamar Made the changes!

2017-06-06 21:40 UTC, knightsamar commented
@DesertBeagle all good, but can we have some paragraph breaks/line spacing added before we merge ? :)

2017-06-06 22:12 UTC, DesertBeagle commented
@knightsamar What do you think of these changes?

2017-06-07 17:14 UTC, knightsamar approved these changes

2017-06-07 20:59 UTC, merged