Add script for building ppc64-diag on debian
osuosl/snippets pull request #7
Opened 2017-10-02 20:01 UTC by doublej472

On [`apt-repo`](https://git.osuosl.org/osuosl/apt-repo) there are packages for ppc64-diag custom built for Debian systems. This is the script that I used for building it and it's requirements, if we ever need to rebuild them in the future. This is meant to be run on an openstack debian instance (ppc64 LE or BE) matching what we would be using on production, and should be entirely self-contained.

I'm documenting this here so I'm not the sole holder of this script and, in the future, we may need to rebuild these with different packages or Debian versions.

2017-10-02 23:53 UTC, Codysseus requested changes

2017-10-02 23:53 UTC, DesertBeagle commented on build-ppc64-diag-debian.sh
> +  "http://archive.ubuntu.com/ubuntu/pool/universe/libs/libservicelog/libservicelog_1.1.14.orig.tar.gz" \
`https` pls

2017-10-02 23:56 UTC, doublej472 commented on build-ppc64-diag-debian.sh
> +  "http://archive.ubuntu.com/ubuntu/pool/universe/libs/libservicelog/libservicelog_1.1.14.orig.tar.gz" \
Doesn't support `https` 😞

2017-10-03 23:27 UTC, Codysseus approved these changes

2017-10-06 20:34 UTC, merged